# Generated by Django 3.1.1 on 2020-09-14 06:32

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.CharField(max_length=15)),
                ('discount_price', models.PositiveIntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DMService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('short_desc', models.CharField(max_length=255)),
                ('long_desc', models.TextField()),
                ('availability', models.BooleanField()),
                ('category', models.ManyToManyField(to='digitalMarketing.Category')),
                ('discount', models.ManyToManyField(to='digitalMarketing.Discount')),
                ('tag', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='DAService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('short_desc', models.CharField(max_length=255)),
                ('long_desc', models.TextField()),
                ('stock', models.PositiveIntegerField()),
                ('availability', models.BooleanField()),
                ('category', models.ManyToManyField(to='digitalMarketing.Category')),
                ('discount', models.ManyToManyField(to='digitalMarketing.Discount')),
                ('tag', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
