# Generated by Django 3.1.1 on 2020-09-18 07:59

import cloudinary.models
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('digitalMarketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daservice',
            name='cover',
            field=cloudinary.models.CloudinaryField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='cover',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dmservice',
            name='cover',
            field=cloudinary.models.CloudinaryField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='daservice',
            name='category',
            field=models.ManyToManyField(blank=True, to='digitalMarketing.Category'),
        ),
        migrations.AlterField(
            model_name='daservice',
            name='discount',
            field=models.ManyToManyField(blank=True, to='digitalMarketing.Discount'),
        ),
        migrations.AlterField(
            model_name='daservice',
            name='tag',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='dmservice',
            name='category',
            field=models.ManyToManyField(blank=True, to='digitalMarketing.Category'),
        ),
        migrations.AlterField(
            model_name='dmservice',
            name='discount',
            field=models.ManyToManyField(blank=True, to='digitalMarketing.Discount'),
        ),
        migrations.AlterField(
            model_name='dmservice',
            name='tag',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
