# Generated by Django 3.1.1 on 2020-09-09 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digitalMarketing', '0002_daservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='daService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('shortDesc', models.CharField(max_length=255)),
                ('longDesc', models.TextField()),
                ('stock', models.IntegerField()),
                ('availability', models.BooleanField()),
                ('category', models.ManyToManyField(to='digitalMarketing.category')),
                ('discount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='digitalMarketing.discount')),
            ],
        ),
        migrations.CreateModel(
            name='dmService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('shortDesc', models.CharField(max_length=255)),
                ('longDesc', models.TextField()),
                ('availability', models.BooleanField()),
                ('category', models.ManyToManyField(to='digitalMarketing.category')),
                ('discount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='digitalMarketing.discount')),
            ],
        ),
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='dmservices',
            name='discount',
        ),
        migrations.DeleteModel(
            name='daServices',
        ),
        migrations.DeleteModel(
            name='dmServices',
        ),
        migrations.AddField(
            model_name='dmservice',
            name='tag',
            field=models.ManyToManyField(to='digitalMarketing.tag'),
        ),
        migrations.AddField(
            model_name='daservice',
            name='tag',
            field=models.ManyToManyField(to='digitalMarketing.tag'),
        ),
    ]
