# Generated by Django 3.1.1 on 2020-09-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalMarketing', '0004_auto_20200909_0653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daservice',
            old_name='itemName',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='daservice',
            old_name='longDesc',
            new_name='long_desc',
        ),
        migrations.RenameField(
            model_name='daservice',
            old_name='shortDesc',
            new_name='short_desc',
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='startDate',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='dmservice',
            old_name='itemName',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='dmservice',
            old_name='longDesc',
            new_name='long_desc',
        ),
        migrations.RenameField(
            model_name='dmservice',
            old_name='shortDesc',
            new_name='short_desc',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='discountPrice',
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='daservice',
            name='category',
            field=models.ManyToManyField(to='digitalMarketing.Category'),
        ),
        migrations.AlterField(
            model_name='daservice',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='daservice',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='daservice',
            name='tag',
            field=models.ManyToManyField(to='digitalMarketing.Tag'),
        ),
        migrations.AlterField(
            model_name='dmservice',
            name='category',
            field=models.ManyToManyField(to='digitalMarketing.Category'),
        ),
        migrations.AlterField(
            model_name='dmservice',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='dmservice',
            name='tag',
            field=models.ManyToManyField(to='digitalMarketing.Tag'),
        ),
    ]
