# Generated by Django 3.1.1 on 2020-09-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalMarketing', '0008_auto_20200911_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daservice',
            name='category',
            field=models.ManyToManyField(to='digitalMarketing.Category'),
        ),
        migrations.AlterField(
            model_name='daservice',
            name='tag',
            field=models.ManyToManyField(to='digitalMarketing.Tag'),
        ),
        migrations.AlterField(
            model_name='dmservice',
            name='category',
            field=models.ManyToManyField(to='digitalMarketing.Category'),
        ),
        migrations.AlterField(
            model_name='dmservice',
            name='tag',
            field=models.ManyToManyField(to='digitalMarketing.Tag'),
        ),
    ]
